language: elixir

elixir:
  - 1.6.6

otp_release:
  - 19.0

env:
  - MIX_ENV=test

before_script:
  - cp config/travis.exs config/test.exs
  - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force

script:
  - mix credo
  - mix coveralls
